language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
script:
  - npm ci && npm run build
install:
  - npm install -g firebase-tools
  - npm install -g create-react-app
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
